<a href="https://colab.research.google.com/github/Sathya-2006/Bakery_site/blob/main/irisflowerclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [ ]:
# 1. Load Data
iris=load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
X,y=iris.data,iris.target

In [ ]:
# 2. Preprocess (Scaling)
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [ ]:
# 3. Train-Test Split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
dt=DecisionTreeClassifier(random_state=42)

In [ ]:
models=[("DecisionTreeClassifier",dt)]
for name,model in models:
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(f'\n{name}')
  print(f'accuracy_score:{accuracy_score(y_test,y_pred)}')
  print(f'classification_report:{classification_report(y_test,y_pred)}')
  print(f'confusion_matrix:{confusion_matrix(y_test,y_pred)}')


DecisionTreeClassifier
accuracy_score:1.0
classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
from sklearn.svm import SVC



In [ ]:
svm=SVC(probability=True,random_state=42)

In [ ]:
models=[("SVM",svm)]
for name,model in models:
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(f'\n{name}')
  print(f'accuracy_score:{accuracy_score(y_test,y_pred)}')
  print(f'classification_report:{classification_report(y_test,y_pred)}')
  print(f'confusion_matrix:{confusion_matrix(y_test,y_pred)}')


SVM
accuracy_score:1.0
classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [ ]:
rf=RandomForestClassifier(random_state=42)

In [ ]:
models=[("RandomForestClassifier",rf)]

In [ ]:
models=[("RandomForestClassifier",rf)]
for name,model in models:
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(f'\n{name}')
  print(f'accuracy:{accuracy_score(y_pred,y_test)}')
  print(f'classification_report:{classification_report(y_pred,y_test)}')
  print(f'confusion_matrix:{confusion_matrix(y_pred,y_test)}')


RandomForestClassifier
accuracy:1.0
classification_report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
# 5. Ensemble (Voting Classifier)
ensemble=VotingClassifier(estimators=models,voting='soft')
ensemble.fit(X_train,y_train)
y_pred=ensemble.predict(X_test)
print('\nEnsemble model')
print(f'Ensemble Accuracy:{accuracy_score(y_test,y_pred)}')
print(f'Ensemble Classification Report:{classification_report(y_test,y_pred)}')


Ensemble model
Ensemble Accuracy:1.0
Ensemble Classification Report:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
from sklearn.model_selection import  cross_val_score, GridSearchCV

In [ ]:
# 6. Cross-validation
scores=cross_val_score(rf,X,y,cv=5)
print("\n random forest cross validation accuracy:",np.mean(scores))


 random forest cross validation accuracy: 0.9666666666666668


In [ ]:
scores=cross_val_score(svm,X,y,cv=5)
print("\n SVM cross validation accuracy:",np.mean(scores))


 SVM cross validation accuracy: 0.9666666666666666


In [ ]:
scores=cross_val_score(dt,X,y,cv=5)
print("\n Decision Tree cross validation accuracy:",np.mean(scores))


 Decision Tree cross validation accuracy: 0.9533333333333334


In [ ]:
scores=cross_val_score(ensemble,X,y,cv=5)
print("\n Ensemble cross validation accuracy:",np.mean(scores))


 Ensemble cross validation accuracy: 0.9666666666666668


In [ ]:
# 7. Hyperparameter Tuning
param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']}
grid = GridSearchCV(SVC(), param_grid, cv=5)
grid.fit(X_train, y_train)
print("\nBest SVM Parameters:", grid.best_params_)
print("Best SVM Score:", grid.best_score_)


Best SVM Parameters: {'C': 10, 'kernel': 'linear'}
Best SVM Score: 0.9583333333333334


In [ ]:
param_grid = {
    'n_estimators': [50, 100, 200],     # number of trees
    'max_depth': [None, 5, 10],         # tree depth
    'min_samples_split': [2, 5, 10]     # minimum samples to split
}

grid=GridSearchCV(RandomForestClassifier(),param_grid,cv=5)
grid.fit(X_train,y_train)
print("\n Best rf classifier:",grid.best_params_)
print("Best randomforest Score:",grid.best_score_)


 Best rf classifier: {'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 200}
Best randomforest Score: 0.9583333333333334


In [ ]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5]
}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,cv=5)
grid.fit(X_train,y_train)
print("\n Best rf classifier:",grid.best_params_)
print("Best decisiontree Score:",grid.best_score_)


 Best rf classifier: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 5, 'min_samples_split': 2}
Best decisiontree Score: 0.95


In [ ]:
!git remote add origin https://github.com/Sathya-2006/irisclassification.git
!git branch -M main
!git push -u origin main

error: remote origin already exists.
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Sathya-2006/irisclassification.git'


In [ ]:
!git init


Reinitialized existing Git repository in /content/irisclassification/.git/


In [ ]:
!mv /content/irisflowerclassification.ipynb /content/irisclassification/


mv: cannot stat '/content/irisflowerclassification.ipynb': No such file or directory


In [ ]:
!git commit -m "Initial commit - Iris classification project"


On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)


In [1]:
!echo "# irisclassification" >> README.md

In [2]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [4]:
!git add README.md

In [5]:
!git commit -m "first commit"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@fb9454e91c03.(none)')
